modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/FastRegions/issues"

[[mixins]]
config="fastregions.mixins.json"
[[mixins]]
config="fastregions.neoforge.mixins.json"

[[mods]]
modId="fastregions"
version="${modVersion}"
displayName="FastRegions"
#updateJSONURL="Modrinth PLEASE add this in the future."
displayURL="https://github.com/TonimatasDEV/FastRegions"
logoFile="logo.png"
credits="TonimatasDEV - Developer"
authors="TonimatasDEV"
description='''
With this mod you can create protected regions in your world.
'''

[[dependencies.fastregions]]
modId="neoforge"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.fastregions]]
modId="minecraft"
type="required"
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"
